### ISSUE TITLE
no Go files in /home/<my username>/go/src/github.com/lxc/lxd

### ISSUE THREAD

**Issue by ang1337** [dobin/yookiterm-lxdserver#1]
I have an issue with installing the LXD server, please can you provide some instructions for proper installation?
My GOPATH is set to $HOME/go and I've cloned the repository into $HOME/go/src

**Comment by tkempheks** [comment]
@ang1337 did you ever resolve this?

**Comment by dobin** [comment]
I will have a look. But I realized that the whole system is kinda hard to set up.

**Comment by dobin** [comment]
Fixed this issue. 

Upgraded to current go modules and dependencies. Some work is still ongoing.
